feature/QPPSF-6837-pcmh-updates
CMSgov/qpp-measures-data pull request #378
Opened 2020-09-21 14:18 UTC by cknightdevelopment

Updated the description of the `IA_PCMH` measure for 2018 & 2020. 

#### Motivation for change

Description was `N/A` not providing details to the users

#### What is being changed

Description of the `IA_PCMH` measure for 2018 & 2020. 

#### Release checklist:
Tasks that must be done prior to merging this PR, including testing.

* [ ] [Package version updated](https://github.com/CMSgov/qpp-measures-data/blob/master/CONTRIBUTING.md#versioning-publishing-and-creating-new-releases)
* [x] Documentation updated
* [x] Unit tests added/passing
* [x] Verified working locally

##### Associated JIRA tickets:
* https://jira.cms.gov/browse/QPPA-6837

2020-09-21 16:51 UTC, branonbarrett approved these changes

2020-09-21 16:58 UTC, nickelstar approved these changes

2020-09-22 13:54 UTC, djacksonsb submitted a review, later dismissed

2020-09-22 15:23 UTC, nickelstar requested changes
Please resolve this conflicting file:
util/measures/2020/ia-measures.csv

2020-09-22 15:47 UTC, chrisknightsb commented
> Please resolve this conflicting file:
> util/measures/2020/ia-measures.csv

done

2020-09-22 15:48 UTC, nickelstar approved these changes

2020-09-22 15:48 UTC, branonbarrett approved these changes

2020-09-22 15:49 UTC, merged