Y5 Measure Schema Changes & Data
CMSgov/qpp-measures-data pull request #443
Opened 2021-04-16 16:21 UTC by pgrocholski

* add allowedPrograms, allowedVendors (for qcdr measures) and requiredForPrograms fields
* populate with preliminary data

##### Associated JIRA tickets:
* https://jira.cms.gov/browse/QPPA-5132
* https://jira.cms.gov/browse/QPPA-4562
* https://jira.cms.gov/browse/QPPA-5133
* https://jira.cms.gov/browse/QPPA-5148

2021-04-16 17:52 UTC, michelingle requested changes
Update Descriptions of new fields in schema file.  See Slack message.
Remove cpcPlus, pcf from MSPB, TPCC, and category = COST measures.

2021-04-21 13:17 UTC, nicholas-gates approved these changes

2021-04-22 13:03 UTC, jeremy-page approved these changes

2021-04-23 22:35 UTC, michelingle approved these changes

2021-04-26 15:11 UTC, merged