QPPA-6097: Update schemas
CMSgov/qpp-measures-data pull request #556
Opened 2022-04-14 16:40 UTC by ckawell

During the Data Dictionary Audit, some measure and benchmark fields were found to be lacking descriptions in their respective schemas. This PR adds descriptions for those fields.

##### Associated JIRA tickets:
* https://jira.cms.gov/browse/QPPA-6097

2022-04-14 21:56 UTC, michelingle requested changes
line 217: Change "Used to truncate submissions data" to "Used to indicate that submissions data should be truncated" ...
line 221: There should be some part of benchmarks that calls out "removed".  Note for next year, we will add back "flat".  So there will be two options: flat, removed.

2022-04-27 17:31 UTC, michelingle requested changes
Line 155: change to similar description as line 213 but change the end to "... listed in clinicalGuidelinesChanged"

2022-05-05 16:58 UTC, michelingle approved these changes

2022-05-05 17:01 UTC, nicholas-gates approved these changes

2022-05-05 17:02 UTC, merged