QPPSE-81_update_benchmarks_2022
CMSgov/qpp-measures-data pull request #687
Opened 2023-05-30 20:20 UTC by varunkarne

#### Motivation for change
PY22 benchmark final update

#### What is being changed
`Benchmarks JSON`

#### Release checklist:
Tasks that must be done prior to merging this PR, including testing.

* [ ] [Package version updated](https://github.com/CMSgov/qpp-measures-data/blob/master/CONTRIBUTING.md#versioning-publishing-and-creating-new-releases)
* [ ] Documentation updated
* [ ] Unit tests added/passing
* [ ] Verified working locally

##### Associated JIRA tickets:
* https://jira.cms.gov/browse/QPPSE-81

2023-05-30 22:23 UTC, michelingle requested changes
Varun, 

1. why are we updating ACEP19 which is a Historic Benchmark, lines 3906-7, 3911-12, 3914-18 (removed)?  Note: the deciles listed on lines 4330 - 4346 added, match what is already in the repo, I was just surprised to see that one indicated as changed.
2. ACMS4, line 4094, 4651 --> There was just a PR to update the HB to be divided by 100.  So line 4094 was 1, instead of 100 after that change.  Can we leave line 4094 at 1?

2023-05-31 11:50 UTC, varunkarne commented
> Varun,
> 
> 1. why are we updating ACEP19 which is a Historic Benchmark, lines 3906-7, 3911-12, 3914-18 (removed)?  Note: the deciles listed on lines 4330 - 4346 added, match what is already in the repo, I was just surprised to see that one indicated as changed.
> 2. ACMS4, line 4094, 4651 --> There was just a PR to update the HB to be divided by 100.  So line 4094 was 1, instead of 100 after that change.  Can we leave line 4094 at 1?

@michelingle
For #1 it was just how the changes diff is showing up, can confirm no changes were made to ACEP19
#2 Updated

2023-05-31 15:28 UTC, michelingle approved these changes

2023-05-31 15:45 UTC, pkasarski approved these changes

2023-05-31 15:47 UTC, merged

2023-05-31 15:47 UTC, KyleApfel approved these changes
Looks good. Thank you.