QPPA-7856-bechmark-input-validation
CMSgov/qpp-measures-data pull request #701
Opened 2023-08-08 21:36 UTC by davidberry-sb

[![ICF](https://th.bing.com/th/id/OIP.3z-X0lRS3oSl7MwvlsX72AAAAA?pid=ImgDet&rs=1)](https://www.icf.com/)

---
## Related Tickets & Documents

https://jira.cms.gov/browse/QPPA-XXXX

---

## Description
See ticket description.

---
## What type of PR is this?

- [ ] 🍕 Feature
- [ ] 🐛 Bug Fix
- [ ] 📝 Documentation Update
- [ ] 🧑‍💻 Code Refactor
- [ ] 🔥 Performance Improvements
- [ ] ✅ Test
- [ ] 🤖 Build
- [ ] 🔁 CI
- [ ] 📦 Chore
- [ ] ⏩ Revert

---

## Added tests?
- [ ] 👍 yes
- [ ] 🙅 no, because they aren't needed
- [ ] 🙋 no, because I need help
---

## Added to documentation?
- [ ] 📜 README.md
- [ ] 📓 Confluence
- [ ] 🙅 no documentation needed

---
### [ ⌥ Optional ] Are there any post-deployment tasks we need to perform?
---

### [ ⌥ Optional] What gif best describes this PR or how it makes you feel?

* For Chromium users: https://chrome.google.com/webstore/detail/gifs-for-github/dkgjnpbipbdaoaadbdhpiokaemhlphep
* For Firefox users: https://addons.mozilla.org/en-US/firefox/addon/gifs-for-github
* After installing the extension, click on the "GIF" button in the comment box and search for a gif that describes your PR!

 <img src="https://media2.giphy.com/media/CkMnLcOgKOxfa/giphy.gif"/>

2023-08-08 21:47 UTC, ckawell-sb approved these changes

2023-08-08 21:50 UTC, ckawell-sb commented on scripts/benchmarks/validation.business.ts
> +          new Error(`Property mismatch for isInverse between Benchmark of id ${benchmarkMeasureId} it's Measure's data. Measure expeceted ${(comparableMeasure as QualityMeasure).isInverse} received $
I think this is supposed to read "and its Measure's data." Missing 'and' and change to 'its'.
Also 'expected' instead of 'expeceted'

2023-08-08 21:50 UTC, ckawell-sb requested changes
Left a comment about the error text after I'd already approved

2023-08-09 13:31 UTC, john-manack approved these changes

2023-08-09 13:38 UTC, nicholas-gates approved these changes

2023-08-09 13:39 UTC, merged